spring.application.name=beedan

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:h2
spring.h2.console.enabled=true

# 애플리케이션 시작 시점에 sql.init 설정 적용
# schema.sql과 data.sql을 자동으로 실행하도록 설정
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8

# JPA Hibenate가 DDL 생성 기능을 사용하지 않도록 설정
# JPA 스키마 자동 생성 X -> SQL로 직접 스키마 관리
spring.jpa.hibernate.ddl-auto=none

# 파일 업로드
upload.stock.dir=./uploads/stock
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# Gemini API
gemini.api-key=AIzaSyAhZZ7NGhgBjVPV_LLD_hH-0NyDOs1LMH8

exchange.api.key=d8a7d3b8ee66b379ffd8b961
exchange.api.url=https://v6.exchangerate-api.com/v6

biz.validation.api.key=1e10d0dc8b417c7ccfdc56a14a1a6d324b8cfee96c343d06bac231400945e733
biz.validation.api.uri=http://api.odcloud.kr/api/nts-businessman/v1/validate

# 전체 로그 레벨 설정 (기본은 INFO)
logging.level.root=INFO

# 내가 만든 패키지의 로그 레벨을 DEBUG로 설정 (가장 상세히 보임)
# 패키지 경로를 본인의 프로젝트 구조에 맞게 수정하세요.
logging.level.com.goodee.beedan=DEBUG

# 로그 출력 형식 커스텀 (선택 사항)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


toss.payments.client-key=test_ck_yL0qZ4G1VOjz59D71a9k3oWb2MQY
toss.payments.secret-key=test_sk_Z1aOwX7K8mX9XZ5A5bq9ryQxzvNP
