spring.application.name=beedan

# H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:beedan
spring.h2.console.enabled=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 애플리케이션 시작 시점에 sql.init 설정 적용
# schema.sql과 data.sql을 자동으로 실행하도록 설정
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8

# JPA Hibenate가 DDL 생성 기능을 사용하지 않도록 설정
# JPA 스키마 자동 생성 X -> SQL로 직접 스키마 관리
spring.jpa.hibernate.ddl-auto=none

# Gemini API
gemini.api-key=AIzaSyB1hX8ZDWGjg1s2O5eT75iqNBDO-t6U-n4
exchange.api.url=https://v6.exchangerate-api.com/v6
exchange.api.key=d8a7d3b8ee66b379ffd8b961

# 네이버 SMTP 서버 정보
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username={your_email_address}
spring.mail.password={app_pass}

# 네이버는 SSL 설정을 true로 해주어야 합니다.
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.starttls.enable=false

# 타임아웃 및 인코딩
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000