-- =====================
-- 최준희 START
-- =====================
CREATE TABLE IF NOT EXISTS stock (
                                     st_id        BIGINT AUTO_INCREMENT PRIMARY KEY,
                                     st_cd        VARCHAR(50),
    br_id        BIGINT,
    st_br_nm     VARCHAR(20),
    st_cat       VARCHAR(20),
    st_cat_nm    VARCHAR(20),
    st_nm        VARCHAR(50),
    st_pr        DECIMAL(10,2),
    st_cur       VARCHAR(5),
    st_img_url   LONGTEXT,
    st_exp_yn    BOOLEAN,
    st_use_yn    BOOLEAN,
    st_del_yn    BOOLEAN,
    st_req_yn    BOOLEAN,
    st_req_mem_id BIGINT,
    st_cra_dt    DATETIME,
    st_cre_dt    DATETIME,
    st_upd_dt    DATETIME,
    st_wis_cnt   BIGINT,
    st_pur_cnt   BIGINT
    );

CREATE TABLE IF NOT EXISTS cart (
                                    ca_id    BIGINT AUTO_INCREMENT PRIMARY KEY,
                                    mem_id   BIGINT,
                                    ca_st_qn BIGINT,
                                    st_id    BIGINT,
                                    FOREIGN KEY (st_id) REFERENCES stock(st_id)
    );

CREATE TABLE IF NOT EXISTS brand (
                                     br_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                     br_nm VARCHAR(25)
    );

CREATE TABLE IF NOT EXISTS category (
                                        cat_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                        cat_nm VARCHAR(25)
    );

CREATE TABLE IF NOT EXISTS crawling_url (
                                            url_id       BIGINT AUTO_INCREMENT PRIMARY KEY,
                                            url_url      VARCHAR(500),
    br_id        BIGINT,
    cat_id       BIGINT,
    url_sel_item VARCHAR(100),
    url_sel_nm   VARCHAR(100),
    url_sel_pr   VARCHAR(100),
    url_sel_img  VARCHAR(300),
    url_cur      VARCHAR(5)
    );

CREATE TABLE IF NOT EXISTS wishlist (
                                        wi_id        BIGINT AUTO_INCREMENT PRIMARY KEY,
                                        st_id        BIGINT,
                                        mem_id       BIGINT,
                                        wi_cre_dt    DATETIME
);
-- =====================
-- 최준희 END
-- =====================



-- =====================
-- 백시현 START
-- =====================


-- =====================
-- 백시현 END
-- =====================



-- =====================
-- 고희권 START
-- =====================
DROP TABLE IF EXISTS member;

CREATE TABLE member (
                        mem_id         BIGINT         NOT NULL AUTO_INCREMENT,
                        mem_lgn_id     VARCHAR(50)    NOT NULL,
                        mem_lgn_pw     VARCHAR(100)   NOT NULL,
                        mem_aut        ENUM('USER', 'ADMIN', 'ROOT') NOT NULL,
                        mem_nm         VARCHAR(50)    NULL,
                        mem_mb_phn     VARCHAR(50)    NULL,
                        mem_ci         VARCHAR(100)   NULL,
                        mem_eml        VARCHAR(50)    NULL,
                        mem_biz_no     VARCHAR(50)    NULL,
                        mem_biz_cre_dt DATETIME       NULL,
                        mem_biz_ttl    VARCHAR(50)    NULL,
                        mem_pos_cd     VARCHAR(100)   NULL,
                        mem_biz_adr    VARCHAR(100)   NULL,
                        mem_biz_dt_adr VARCHAR(100)   NULL,
                        mem_ceo_nm     VARCHAR(50)    NULL,
                        mem_ceo_phn    VARCHAR(50)    NULL,
                        mem_cmp_tel    VARCHAR(50)    NULL,
                        mem_lgn_tr     BIGINT         NOT NULL DEFAULT 0,
                        mem_loc_dt     DATETIME       NULL,
                        mem_stt        ENUM('ACTIVE', 'INACTIVE', 'LOCK') NOT NULL DEFAULT 'ACTIVE',
                        mem_upd_id     BIGINT         NULL,
                        mem_upd_dt     DATETIME       DEFAULT CURRENT_TIMESTAMP,
                        mem_cre_dt     DATETIME       DEFAULT CURRENT_TIMESTAMP,

                        PRIMARY KEY (mem_id),
                        CONSTRAINT uk_mem_lgn_id UNIQUE (mem_lgn_id) -- H2와 MySQL 모두 호환되는 문법
);
-- =====================
-- 고희권 END
-- =====================



-- =====================
-- 장 준 START
-- =====================
CREATE TABLE chatbot_topic (
   cb_tp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cb_tp_nm VARCHAR(100) NOT NULL,
   cb_tp_lvl INT NOT NULL,
   cb_tp_ord INT NOT NULL,
   cb_tp_use_yn BOOLEAN NOT NULL DEFAULT TRUE,
   cb_tp_cre_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   cb_tp_upd_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   cb_tp_prn_id BIGINT NULL, -- FK
   -- 1차 질의는 cb_tp_prn_id 가 NULL 이라 UNIQUE 만으로 순서 중복 방지가 불완전할 수 있으므로 서비스에서도 중복 검사 필요
   UNIQUE (cb_tp_prn_id, cb_tp_ord),
   CHECK (cb_tp_lvl IN (1, 2)),
   CHECK (
      (cb_tp_lvl = 1 AND cb_tp_prn_id IS NULL)
      OR
      (cb_tp_lvl = 2 AND cb_tp_prn_id IS NOT NULL)
   )
);

CREATE TABLE chatbot_response (
  cb_res_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cb_res_ttl VARCHAR(255) NOT NULL,
  cb_res_con CLOB NOT NULL,
  cb_res_lnk_btn_nm VARCHAR(100) NULL,
  cb_res_lnk_url VARCHAR(255) NULL,
  cb_res_use_yn BOOLEAN NOT NULL DEFAULT TRUE,
  cb_res_cre_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cb_res_upd_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cb_tp_id BIGINT NOT NULL UNIQUE, -- FK
  CHECK (
    (cb_res_lnk_btn_nm IS NULL AND cb_res_lnk_url IS NULL)
    OR
    (cb_res_lnk_btn_nm IS NOT NULL AND cb_res_lnk_url IS NOT NULL)
  )
);

CREATE TABLE chat_room (
   ch_ro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ch_ro_ttl VARCHAR(255) NOT NULL,
   ch_ro_stt VARCHAR(20) NOT NULL,
   ch_ro_cre_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ch_ro_asg_dt TIMESTAMP NULL,
   ch_ro_cls_dt TIMESTAMP NULL,
   ch_ro_cls_rsn VARCHAR(20) NULL,
   ch_ro_last_ms_dt TIMESTAMP NULL,
   mem_id BIGINT NOT NULL, -- FK
   mem_ad_id BIGINT NULL, -- FK
   CHECK (ch_ro_stt IN ('OPEN', 'ONGOING', 'CLOSED')),
   CHECK (ch_ro_cls_rsn IS NULL OR ch_ro_cls_rsn IN ('USER', 'ADMIN', 'AUTO')),
   CHECK (
      (ch_ro_stt IN ('OPEN', 'ONGOING') AND ch_ro_cls_dt IS NULL AND ch_ro_cls_rsn IS NULL)
      OR
      (ch_ro_stt = 'CLOSED' AND ch_ro_cls_dt IS NOT NULL AND ch_ro_cls_rsn IS NOT NULL)
   ),
   CHECK (
      (ch_ro_stt = 'OPEN' AND mem_ad_id IS NULL)
      OR
      (ch_ro_stt IN ('ONGOING', 'CLOSED') AND mem_ad_id IS NOT NULL)
   )
);

CREATE TABLE chat_message (
  ch_ms_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ch_ms_sen_ty VARCHAR(20) NOT NULL,
  ch_ms_con CLOB NOT NULL,
  ch_ms_cre_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ch_ro_id BIGINT NOT NULL, -- FK
  mem_id BIGINT NOT NULL, -- FK
  CHECK (ch_ms_sen_ty IN ('USER', 'ADMIN'))
);

CREATE TABLE chat_room_read_status (
   ch_ro_re_st_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   ch_ro_re_st_last_dt TIMESTAMP NULL,
   ch_ro_re_st_unr_yn BOOLEAN NOT NULL DEFAULT FALSE,
   ch_ro_id BIGINT NOT NULL, -- FK
   mem_id BIGINT NOT NULL, -- FK
   ch_ms_last_id BIGINT NULL, -- FK
   UNIQUE (mem_id, ch_ro_id)
);
-- =====================
-- 장 준 END
-- =====================



-- =====================
-- 임 욱 START
-- =====================
-- =====================
-- 임 욱 END
-- =====================
